name: create pull request

on:
  pull_request:
    branches: ["123"]

jobs:
  create-pr-on-push:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        head: main
        base: 123
        title: "자동 생성 PR"
