name: create pull request

on:
  push:
    branches: ['main']

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Create pull request Admin Team
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        head: main
        base: Admin_team
        title: "자동 생성 PR To Admin Team"

    - name: Create pull request Kiosk Team
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        head: main
        base: Kiosk_team
        title: "자동 생성 PR To Kiosk Team"

    - name: Create pull request Main Team
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        head: main
        base: Main_team
        title: "자동 생성 PR To Main Team"
