name: accept pull request

on:
  pull_request:
    branches: ['123']

jobs:
  recive_merge:
    runs-on: ubuntu-latest
    steps:   
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      env:
          PR_NUMBER: ${{ github.event.number }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ env.PR_NUMBER }}
        method: squash # merge rebase
        repo: juliangruber/octokit-action
